version: '3.4'
services:
  frontend:
    container_name: devops_frontend
    command: npm run dev
    build:
      context: .

    ports:
      - 3000:3000
    volumes:
      - ./:/app
#       - /app/node_modules
#       - /app/.next
